[project]
name = "maup"
version = "2.1.0"
description = "The geospatial toolkit for redistricting data"
authors = [
    { name = "Metric Geometry and Gerrymandering Group", email = "dev@mggg.org" },
    { name = "Max Hully", email = "max@mggg.org" },
    { name = "Max Fan", email = "root@max.fan" },
    { name = "Jeanne Clelland", email = "jnclelland@colorado.edu" },
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.11,<=3.15"
keywords = ["geospatial", "redistricting", "gis"]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy>=2.4.6,<3.0.0; python_version < '3.12'",
    "numpy>=2.5.3,<3.0.0; python_version >= '3.12'",
    "pandas>=2.3.3,<3.0.0",
    "geopandas>=1.1.4,<2.0.0",
    "shapely>=2.1.2,<3.0.0",
    "tqdm>=4.70.1,<5.0.0",
    "pyproj>=3.7.2; python_version < '3.12'",
    "pyproj>=3.8.0; python_version >= '3.12'",
    "pyogrio>=0.13.0,<0.14.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1,<10.0.0",
    "pytest-cov>=7.1.0,<8.0.0",
    "sphinx>=8.2.3,<9.0.0",
    "numpydoc>=1.9.0,<2.0.0",
    "pydata-sphinx-theme>=0.16.1,<0.17.0",
    "myst-parser>=4.0.1,<5.0.0",
    "sphinx-copybutton>=0.5.2,<0.6.0",
    "sphinx-rtd-theme>=3.1.0,<4.0.0",
    "black>=26.5.1,<27.0.0",
    "ipykernel>=7.3.0,<8.0.0",
    "python-dateutil>=2.9.0.post0,<3.0.0",
]

[tool.poetry]
requires-poetry = ">=2.2"
packages = [{ include = "maup" }]
include = ["best-practices.md"]
exclude = ["examples", "tests"]

[build-system]
requires = ["poetry-core>=2.2.0"]
build-backend = "poetry.core.masonry.api"
